image:
  repository: genomenexus/gn-mongo
  tag: 0.32_grch38_ensembl95
  pullPolicy: Always
persistence:
  enabled: true
  size: 20Gi
nodeSelector:
  eks.amazonaws.com/nodegroup: "gn-grch38"
tolerations:
  - key: "workload"
    operator: "Equal"
    value: "gn-grch38"
    effect: "NoSchedule"